# Move to ~/.zprofile

# Define macOS system path if needed
# PATH=/usr/local/bin:/usr/bin:/usr/sbin:/bin:/sbin
# export PATH

# If needed, insert custom path logic before `:${PATH}`
# export PATH=":${PATH}"
