# Move to ~/.zprofile

# OSX default path
PATH=/usr/local/bin:/usr/bin:/usr/sbin:/bin:/sbin
export PATH

# Custom path logic
export PATH="${HOME}/bin:${HOME}/.cargo/bin:/usr/local/opt/php@7.2/bin:/usr/local/opt/php@7.2/sbin:/usr/local/opt/ruby/bin:/usr/local/lib/ruby/gems/2.6.0/bin:${PATH}"
